### ISSUE TITLE
Dostępność

### ISSUE THREAD

**Issue by radluki** [MPKowalczyk/Wahadlo#3]
Widzę, że jest porobionych kilka branchów. Nie mam do nich dostępu. Czy tak ma byc? Jeśli tak to nie zapominajcie o mergach do mastera, żeby był łatwy przegląd postępów.

**Comment by kalelek** [comment]
Powinieneś mieć dostęp też do branchów Model i Komunikacja

**Comment by radluki** [comment]
Sprawdziłem jeszcze raz i już mam dostęp.
